### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dataknut**
you’ll love this :-) - read all the commits!

### CODE REVIEW

**Comment by developius** [comment]
Oh god, what is it with you and not using capitals to start your titles? Read [this](http://chris.beams.io/posts/git-commit/) - all of it.

**Comment by dataknut** [comment]
what titles?

**Comment by developius** [comment]
Commit titles, of the 28 commits in this pull request, there is _one_ commit title that starts with a capital letter. If I'd integrated the automated commit format restrictions, that'd be a 96.4% failure rate.

**Comment by dataknut** [comment]
Yeah but you're a human so you have discretion

**Pull request merged**
